import {
  BagIcon,
  BagSecondIcon,
  CakeIcon,
  CalendarIcon,
  CheckCircleSecondIcon,
  CheckCircleIcon,
  ChefIcon,
  ChevronRightIcon,
  ClockFourIcon,
  ClockNineIcon,
  CloudIcon,
  CoffeeIcon,
  ComputersIcon,
  CreditCardIcon,
  DiscountIcon,
  DishwasherIcon,
  DollarCircleIcon,
  GiftIcon,
  HomeIcon,
  LibraIcon,
  ListIcon,
  MinusCircleIcon,
  NoteIcon,
  PersonCircleIcon,
  PhoneIcon,
  PlusCircleIcon,
  PlusIcon,
  QuestionIcon,
  RepeatIcon,
  RockIcon,
  ScooterIcon,
  SpecialIcon,
  StarIcon,
  SwitchIcon,
  WaiterIcon,
  WarningIcon,
  PluginIcon,
  BarsIcon,
  MapIcon,
  DownloadIcon,
  SpeedometerIcon,
  CommutatorIcon,
  HeartIcon,
  LaptopComputerIcon,
  GraduationIcon,
  LaughingFaceIcon,
  SmileyFaceIcon,
  TheaterFaceIcon,
  WorkBriefcaseIcon,
  WritingPenIcon,
  BabyIcon,
  BenchIcon,
  BusinessManIcon,
  BoothIcon,
  DisabilityIcon,
  CigaretteIcon,
  VolumeOffIcon,
  WindowIcon,
  ChefSecondIcon,
  FishIcon,
  MilkIcon,
  SadFaceIcon,
  SaladIcon,
  GlutenFreeIcon,
  HinduismIcon,
  LeafIcon,
  ApartmentIcon,
  CashIcon,
  CreditCardSecondIcon,
  ExpandFullscreenIcon,
  GroupPeopleIcon,
  HistoryIcon,
  LocationPinIcon,
  MapSecondIcon,
  NoteSecondIcon,
  SearchIcon,
  BurgerRoundedIcon,
  ChatBubbleIcon,
  ChatBubblesIcon,
  HouseIcon,
  MailIcon,
  StackedCirclesIcon,
  TableIcon,
  UpSquareIcon,
  VipIcon,
  XIcon,
  DepositCashIcon,
  FastFoodIcon,
  ManCircleSecondIcon,
  MoneyDocumentIcon,
  PrinterIcon,
  RepeatSecondIcon,
  SilverwareIcon,
  StoreIcon,
  WalletCashIcon,
  WithdrawCashIcon,
  CashRegisterIcon,
  ChairIcon,
  ComputerIcon,
  ContinuedCirclesIcon,
  GivingHandIcon,
  HomeSecondIcon,
  MailSecondIcon,
  RightDirectionArrowIcon,
  SearchUsersIcon,
  SpecialSecondIcon,
} from "nexticons-react/solid";
import { IconList } from "../IconList";

const icons = [
  {
    name: "CheckCircleIcon",
    icon: <CheckCircleIcon className="next-icon" />,
  },
  {
    name: "CheckCircleSecondIcon",
    icon: <CheckCircleSecondIcon className="next-icon" />,
  },
  {
    name: "ClockFourIcon",
    icon: <ClockFourIcon className="next-icon" />,
  },
  {
    name: "ClockNineIcon",
    icon: <ClockNineIcon className="next-icon" />,
  },
  {
    name: "DollarCircleIcon",
    icon: <DollarCircleIcon className="next-icon" />,
  },
  {
    name: "PlusCircleIcon",
    icon: <PlusCircleIcon className="next-icon" />,
  },
  {
    name: "MinusCircleIcon",
    icon: <MinusCircleIcon className="next-icon" />,
  },

  {
    name: "PersonCircleIcon",
    icon: <PersonCircleIcon className="next-icon" />,
  },
  {
    name: "ChevronRightIcon",
    icon: <ChevronRightIcon className="next-icon" />,
  },
  { name: "PlusIcon", icon: <PlusIcon className="next-icon" /> },
  { name: "RepeatIcon", icon: <RepeatIcon className="next-icon" /> },
  { name: "SwitchIcon", icon: <SwitchIcon className="next-icon" /> },
  { name: "ListIcon", icon: <ListIcon className="next-icon" /> },
  { name: "ChefIcon", icon: <ChefIcon className="next-icon" /> },
  { name: "ChefSecondIcon", icon: <ChefSecondIcon className="next-icon" /> },
  { name: "CloudIcon", icon: <CloudIcon className="next-icon" /> },
  { name: "CoffeeIcon", icon: <CoffeeIcon className="next-icon" /> },
  {
    name: "DiscountIcon",
    icon: <DiscountIcon className="next-icon" />,
  },
  {
    name: "DishwasherIcon",
    icon: <DishwasherIcon className="next-icon" />,
  },
  { name: "HomeIcon", icon: <HomeIcon className="next-icon" /> },
  { name: "PhoneIcon", icon: <PhoneIcon className="next-icon" /> },
  { name: "RockIcon", icon: <RockIcon className="next-icon" /> },
  { name: "ScooterIcon", icon: <ScooterIcon className="next-icon" /> },
  { name: "SpecialIcon", icon: <SpecialIcon className="next-icon" /> },
  { name: "StarIcon", icon: <StarIcon className="next-icon" /> },
  { name: "WaiterIcon", icon: <WaiterIcon className="next-icon" /> },
  { name: "WarningIcon", icon: <WarningIcon className="next-icon" /> },
  { name: "BagIcon", icon: <BagIcon className="next-icon" /> },
  { name: "BagSecondIcon", icon: <BagSecondIcon className="next-icon" /> },
  {
    name: "BarsIcon",
    icon: <BarsIcon className="next-icon"/>,
  },
  {
    name: "CommutatorIcon",
    icon: <CommutatorIcon  className="next-icon"/>,
  },
  {
    name: "ComputersIcon",
    icon: <ComputersIcon className="next-icon" />,
  },
  {
    name: "DownloadIcon",
    icon: <DownloadIcon className="next-icon"/>,
  },
  {
    name: "LibraIcon",
    icon: <LibraIcon className="next-icon" />,
  },
  {
    name: "MapIcon",
    icon: <MapIcon className="next-icon"/>,
  },
  {
    name: "PluginIcon",
    icon: <PluginIcon className="next-icon"/>,
  },
  {
    name: "SpeedometerIcon",
    icon: <SpeedometerIcon className="next-icon"/>,
  },
  { name: "CakeIcon", icon: <CakeIcon className="next-icon" /> },

  { name: "CalendarIcon", icon: <CalendarIcon className="next-icon" /> },
  { name: "NoteIcon", icon: <NoteIcon className="next-icon" /> },
  {
    name: "GiftIcon",
    icon: <GiftIcon className="next-icon" />,
  },
  {
    name: "CreditCardIcon",
    icon: <CreditCardIcon className="next-icon" />,
  },
  {
    name: "QuestionIcon",
    icon: <QuestionIcon className="next-icon" />,
  },
  {
    name: "HeartIcon",
    icon: <HeartIcon className="next-icon" />,
  },
  {
    name: "LaptopComputerIcon",
    icon: <LaptopComputerIcon className="next-icon" />,
  },
  {
    name: "GraduationIcon",
    icon: <GraduationIcon className="next-icon" />,
  },
  {
    name: "LaughingFaceIcon",
    icon: <LaughingFaceIcon className="next-icon" />,
  },
  {
    name: "SmileyFaceIcon",
    icon: <SmileyFaceIcon className="next-icon" />,
  },
  {
    name: "TheaterFaceIcon",
    icon: <TheaterFaceIcon className="next-icon" />,
  },
  {
    name: "WorkBriefcaseIcon",
    icon: <WorkBriefcaseIcon className="next-icon" />,
  },
  {
    name: "WritingPenIcon",
    icon: <WritingPenIcon className="next-icon" />,
  },
  {
    name: "BabyIcon",
    icon: <BabyIcon className="next-icon" />,
  },
  {
    name: "BenchIcon",
    icon: <BenchIcon className="next-icon" />,
  },
  {
    name: "BusinessManIcon",
    icon: <BusinessManIcon className="next-icon" />,
  },
  {
    name: "BoothIcon",
    icon: <BoothIcon className="next-icon" />,
  },
  {
    name: "DisabilityIcon",
    icon: <DisabilityIcon className="next-icon" />,
  },
  {
    name: "CigaretteIcon",
    icon: <CigaretteIcon className="next-icon" />,
  },
  {
    name: "VolumeOffIcon",
    icon: <VolumeOffIcon className="next-icon" />,
  },
  {
    name: "WindowIcon",
    icon: <WindowIcon className="next-icon" />,
  },
  {  name: "FishIcon", icon: <FishIcon className="next-icon" /> },
  {  name: "MilkIcon", icon: <MilkIcon className="next-icon" /> },
  {  name: "SadFaceIcon", icon: <SadFaceIcon className="next-icon" /> },
  {  name: "SaladIcon", icon: <SaladIcon className="next-icon" /> },
  {  name: "GlutenFreeIcon", icon: <GlutenFreeIcon className="next-icon" /> },
  {  name: "HinduismIcon", icon: <HinduismIcon className="next-icon" /> },
  {  name: "LeafIcon", icon: <LeafIcon className="next-icon" /> },
  {  name: "ApartmentIcon", icon: <ApartmentIcon className="next-icon" /> },
  {  name: "CashIcon", icon: <CashIcon className="next-icon" /> },
  {  name: "CreditCardSecondIcon", icon: <CreditCardSecondIcon className="next-icon" /> },
  {  name: "ExpandFullscreenIcon", icon: <ExpandFullscreenIcon className="next-icon" /> },
  {  name: "GroupPeopleIcon", icon: <GroupPeopleIcon className="next-icon" /> },
  {  name: "HistoryIcon", icon: <HistoryIcon className="next-icon" /> },
  {  name: "LocationPinIcon", icon: <LocationPinIcon className="next-icon" /> },
  {  name: "MapSecondIcon", icon: <MapSecondIcon className="next-icon" /> },
  {  name: "NoteSecondIcon", icon: <NoteSecondIcon className="next-icon" /> },
  {  name: "SearchIcon", icon: <SearchIcon className="next-icon" /> },
  {  name: "", icon: <div /> },
  {  name: "BurgerRoundedIcon", icon: <BurgerRoundedIcon className="next-icon" /> },
  {  name: "ChatBubbleIcon", icon: <ChatBubbleIcon className="next-icon" /> },
  {  name: "ChatBubblesIcon", icon: <ChatBubblesIcon className="next-icon" /> },
  {  name: "HouseIcon", icon: <HouseIcon className="next-icon" /> },
  {  name: "MailIcon", icon: <MailIcon className="next-icon" /> },
  {  name: "StackedCirclesIcon", icon: <StackedCirclesIcon className="next-icon" /> },
  {  name: "TableIcon", icon: <TableIcon className="next-icon" /> },
  {  name: "UpSquareIcon", icon: <UpSquareIcon className="next-icon" /> },
  {  name: "VipIcon", icon: <VipIcon className="next-icon" /> },
  {  name: "XIcon", icon: <XIcon className="next-icon" /> },
  {  name: "", icon: <div /> },
  {  name: "DepositCashIcon", icon: <DepositCashIcon className="next-icon" /> },
  {  name: "FastFoodIcon", icon: <FastFoodIcon className="next-icon" /> },
  {  name: "ManCircleSecondIcon", icon: <ManCircleSecondIcon className="next-icon" /> },
  {  name: "MoneyDocumentIcon", icon: <MoneyDocumentIcon className="next-icon" /> },
  {  name: "PrinterIcon", icon: <PrinterIcon className="next-icon" /> },
  {  name: "RepeatSecondIcon", icon: <RepeatSecondIcon className="next-icon" /> },
  {  name: "SilverwareIcon", icon: <SilverwareIcon className="next-icon" /> },
  {  name: "StoreIcon", icon: <StoreIcon className="next-icon" /> },
  {  name: "WalletCashIcon", icon: <WalletCashIcon className="next-icon" /> },
  {  name: "WithdrawCashIcon", icon: <WithdrawCashIcon className="next-icon" /> },
  {  name: "CashRegisterIcon", icon: <CashRegisterIcon className="next-icon" /> },
  {  name: "ChairIcon", icon: <ChairIcon className="next-icon" /> },
  {  name: "ComputerIcon", icon: <ComputerIcon className="next-icon" /> },
  {  name: "ContinuedCirclesIcon", icon: <ContinuedCirclesIcon className="next-icon" /> },
  {  name: "GivingHandIcon", icon: <GivingHandIcon className="next-icon" /> },
  {  name: "HomeSecondIcon", icon: <HomeSecondIcon className="next-icon" /> },
  {  name: "MailSecondIcon", icon: <MailSecondIcon className="next-icon" /> },
  {  name: "RightDirectionArrowIcon", icon: <RightDirectionArrowIcon className="next-icon" /> },
  {  name: "SearchUsersIcon", icon: <SearchUsersIcon className="next-icon" /> },
  {  name: "SpecialSecondIcon", icon: <SpecialSecondIcon className="next-icon" /> },
  // {  name: "", icon: < className="next-icon" /> },
];

export const SolidIcons = ({searchStr}) => {
  return <IconList searchStr={searchStr} list={icons} />;
};
