import {
AirplaneIcon,
ApartmentIcon,
ArrowDownIcon,
ArrowLeftIcon,
ArrowRightIcon,
ArrowUpIcon,
BabyIcon,
BackCircleIcon,
BagIcon,
BagSecondIcon,
BankIcon,
BarsIcon,
BarsSecondIcon,
BarsSquareIcon,
BellIcon,
BenchIcon,
BoothIcon,
BrushIcon,
BuildingIcon,
BurgerIcon,
BurgerRoundedIcon,
BusinessManIcon,
CakeIcon,
CalendarIcon,
CalendarSecondIcon,
CalendarTimeIcon,
CarIcon,
CarSecondIcon,
CashIcon,
CashRegisterIcon,
CashRegisterSecondIcon,
ChairIcon,
ChatBubbleIcon,
ChatBubblesIcon,
CheckCircleIcon,
CheckCircleSecondIcon,
CheckDroppedIcon,
CheckIcon,
ChefIcon,
ChefSecondIcon,
ChevronDownIcon,
ChevronDownSquareIcon,
ChevronLeftIcon,
ChevronLeftSquareIcon,
ChevronRightIcon,
ChevronRightSquareIcon,
ChevronUpIcon,
ChevronUpSquareIcon,
CigaretteIcon,
CircleGraphIcon,
CircleIcon,
CleanerIcon,
ClipboardListIcon,
ClockFourIcon,
ClockNineIcon,
CloudIcon,
CoffeeIcon,
CommutatorIcon,
ComputerIcon,
ComputersIcon,
ContinuedCirclesIcon,
CouponIcon,
CreditCardIcon,
CreditCardReaderIcon,
CreditCardSecondIcon,
DepositCashIcon,
DessertIcon,
DineInIcon,
DinnerPlatterIcon,
DirectionLeftArrowIcon,
DirectionLeftSecondArrowIcon,
DirectionRightArrowIcon,
DirectionRightSecondArrowIcon,
DirectionsIcon,
DisabilityIcon,
DiscountIcon,
DishwasherIcon,
DollarBillsIcon,
DollarCircleIcon,
DollarIcon,
DollarSquareIcon,
DomainIcon,
DownloadIcon,
EquallyIcon,
ExpandFullscreenIcon,
FastFoodIcon,
FingerIcon,
FingerPressIcon,
FishIcon,
GiftIcon,
GivingHandIcon,
GlutenFreeIcon,
GraduationIcon,
GroupPeopleIcon,
HeartIcon,
HeartMonitorIcon,
HinduismIcon,
HistoryIcon,
HoldIcon,
HomeIcon,
HomeSecondIcon,
HouseIcon,
HouseSecondIcon,
InfoIcon,
InfoThickIcon,
LaptopComputerIcon,
LaughingFaceIcon,
LeafIcon,
LibraIcon,
ListIcon,
LoadingIcon,
LocationPinIcon,
MailIcon,
MailSecondIcon,
ManCircleSecondIcon,
MapIcon,
MapSecondIcon,
MembershipIcon,
MenuIcon,
MilkIcon,
MinusCircleIcon,
MinusIcon,
MinusRoundedIcon,
MinusRoundedThickIcon,
MinusThickIcon,
MobileIcon,
ModifyIcon,
MoneyDocumentIcon,
MoneyIcon,
MonitorIcon,
MoonIcon,
NextIcon,
NoteIcon,
NoteSecondIcon,
OpenBookIcon,
PeopleIcon,
PerItemIcon,
PercentCircleIcon,
PersonCircleIcon,
PersonIcon,
PersonSecondCircleIcon,
PersonSecondIcon,
PersonSquareIcon,
PhoneIcon,
PickUpIcon,
PlayIcon,
PluginIcon,
PlusCircleIcon,
PlusIcon,
PlusRoundedIcon,
PlusRoundedThickIcon,
PlusThickIcon,
PositiveBarGraphIcon,
PrintIcon,
PrinterIcon,
PrinterSecondIcon,
QuestionCircleIcon,
QuestionIcon,
QuestionSquareIcon,
RepeatCircleIcon,
RepeatIcon,
RepeatSecondIcon,
ResizeIcon,
RockIcon,
SadFaceIcon,
SaladIcon,
ScooterIcon,
SearchIcon,
SearchUsersIcon,
SeatedIcon,
ServerIcon,
SetLocationIcon,
SettingsIcon,
SilverwareIcon,
SmileyFaceIcon,
SortIcon,
SpecialIcon,
SpecialSecondIcon,
SpeedometerIcon,
StackedCirclesIcon,
StarIcon,
StarListIcon,
StarSecondIcon,
StoreIcon,
SubscriberIcon,
SwitchIcon,
SymbolsIcon,
TableIcon,
TheaterFaceIcon,
TopArrowCircleIcon,
TrashIcon,
UpSquareIcon,
UpdatesIcon,
VipIcon,
VolumeOffIcon,
WaiterIcon,
WalkInIcon,
WalkingPersonIcon,
WalletCashIcon,
WarningIcon,
WindowIcon,
WithdrawCashIcon,
WorkBriefcaseIcon,
WorldIcon,
WorldSecondIcon,
WritingPenIcon,
XIcon,
XRoundedIcon,
XSquareIcon,
ZoomInIcon,
ZoomOutIcon,
} from "nexticons/solid";
  

 
const icons = [
{name: "AirplaneIcon", icon: <AirplaneIcon className="next-icon" />}, 
{name: "ApartmentIcon", icon: <ApartmentIcon className="next-icon" />}, 
{name: "ArrowDownIcon", icon: <ArrowDownIcon className="next-icon" />}, 
{name: "ArrowLeftIcon", icon: <ArrowLeftIcon className="next-icon" />}, 
{name: "ArrowRightIcon", icon: <ArrowRightIcon className="next-icon" />}, 
{name: "ArrowUpIcon", icon: <ArrowUpIcon className="next-icon" />}, 
{name: "BabyIcon", icon: <BabyIcon className="next-icon" />}, 
{name: "BackCircleIcon", icon: <BackCircleIcon className="next-icon" />}, 
{name: "BagIcon", icon: <BagIcon className="next-icon" />}, 
{name: "BagSecondIcon", icon: <BagSecondIcon className="next-icon" />}, 
{name: "BankIcon", icon: <BankIcon className="next-icon" />}, 
{name: "BarsIcon", icon: <BarsIcon className="next-icon" />}, 
{name: "BarsSecondIcon", icon: <BarsSecondIcon className="next-icon" />}, 
{name: "BarsSquareIcon", icon: <BarsSquareIcon className="next-icon" />}, 
{name: "BellIcon", icon: <BellIcon className="next-icon" />}, 
{name: "BenchIcon", icon: <BenchIcon className="next-icon" />}, 
{name: "BoothIcon", icon: <BoothIcon className="next-icon" />}, 
{name: "BrushIcon", icon: <BrushIcon className="next-icon" />}, 
{name: "BuildingIcon", icon: <BuildingIcon className="next-icon" />}, 
{name: "BurgerIcon", icon: <BurgerIcon className="next-icon" />}, 
{name: "BurgerRoundedIcon", icon: <BurgerRoundedIcon className="next-icon" />}, 
{name: "BusinessManIcon", icon: <BusinessManIcon className="next-icon" />}, 
{name: "CakeIcon", icon: <CakeIcon className="next-icon" />}, 
{name: "CalendarIcon", icon: <CalendarIcon className="next-icon" />}, 
{name: "CalendarSecondIcon", icon: <CalendarSecondIcon className="next-icon" />}, 
{name: "CalendarTimeIcon", icon: <CalendarTimeIcon className="next-icon" />}, 
{name: "CarIcon", icon: <CarIcon className="next-icon" />}, 
{name: "CarSecondIcon", icon: <CarSecondIcon className="next-icon" />}, 
{name: "CashIcon", icon: <CashIcon className="next-icon" />}, 
{name: "CashRegisterIcon", icon: <CashRegisterIcon className="next-icon" />}, 
{name: "CashRegisterSecondIcon", icon: <CashRegisterSecondIcon className="next-icon" />}, 
{name: "ChairIcon", icon: <ChairIcon className="next-icon" />}, 
{name: "ChatBubbleIcon", icon: <ChatBubbleIcon className="next-icon" />}, 
{name: "ChatBubblesIcon", icon: <ChatBubblesIcon className="next-icon" />}, 
{name: "CheckCircleIcon", icon: <CheckCircleIcon className="next-icon" />}, 
{name: "CheckCircleSecondIcon", icon: <CheckCircleSecondIcon className="next-icon" />}, 
{name: "CheckDroppedIcon", icon: <CheckDroppedIcon className="next-icon" />}, 
{name: "CheckIcon", icon: <CheckIcon className="next-icon" />}, 
{name: "ChefIcon", icon: <ChefIcon className="next-icon" />}, 
{name: "ChefSecondIcon", icon: <ChefSecondIcon className="next-icon" />}, 
{name: "ChevronDownIcon", icon: <ChevronDownIcon className="next-icon" />}, 
{name: "ChevronDownSquareIcon", icon: <ChevronDownSquareIcon className="next-icon" />}, 
{name: "ChevronLeftIcon", icon: <ChevronLeftIcon className="next-icon" />}, 
{name: "ChevronLeftSquareIcon", icon: <ChevronLeftSquareIcon className="next-icon" />}, 
{name: "ChevronRightIcon", icon: <ChevronRightIcon className="next-icon" />}, 
{name: "ChevronRightSquareIcon", icon: <ChevronRightSquareIcon className="next-icon" />}, 
{name: "ChevronUpIcon", icon: <ChevronUpIcon className="next-icon" />}, 
{name: "ChevronUpSquareIcon", icon: <ChevronUpSquareIcon className="next-icon" />}, 
{name: "CigaretteIcon", icon: <CigaretteIcon className="next-icon" />}, 
{name: "CircleGraphIcon", icon: <CircleGraphIcon className="next-icon" />}, 
{name: "CircleIcon", icon: <CircleIcon className="next-icon" />}, 
{name: "CleanerIcon", icon: <CleanerIcon className="next-icon" />}, 
{name: "ClipboardListIcon", icon: <ClipboardListIcon className="next-icon" />}, 
{name: "ClockFourIcon", icon: <ClockFourIcon className="next-icon" />}, 
{name: "ClockNineIcon", icon: <ClockNineIcon className="next-icon" />}, 
{name: "CloudIcon", icon: <CloudIcon className="next-icon" />}, 
{name: "CoffeeIcon", icon: <CoffeeIcon className="next-icon" />}, 
{name: "CommutatorIcon", icon: <CommutatorIcon className="next-icon" />}, 
{name: "ComputerIcon", icon: <ComputerIcon className="next-icon" />}, 
{name: "ComputersIcon", icon: <ComputersIcon className="next-icon" />}, 
{name: "ContinuedCirclesIcon", icon: <ContinuedCirclesIcon className="next-icon" />}, 
{name: "CouponIcon", icon: <CouponIcon className="next-icon" />}, 
{name: "CreditCardIcon", icon: <CreditCardIcon className="next-icon" />}, 
{name: "CreditCardReaderIcon", icon: <CreditCardReaderIcon className="next-icon" />}, 
{name: "CreditCardSecondIcon", icon: <CreditCardSecondIcon className="next-icon" />}, 
{name: "DepositCashIcon", icon: <DepositCashIcon className="next-icon" />}, 
{name: "DessertIcon", icon: <DessertIcon className="next-icon" />}, 
{name: "DineInIcon", icon: <DineInIcon className="next-icon" />}, 
{name: "DinnerPlatterIcon", icon: <DinnerPlatterIcon className="next-icon" />}, 
{name: "DirectionLeftArrowIcon", icon: <DirectionLeftArrowIcon className="next-icon" />}, 
{name: "DirectionLeftSecondArrowIcon", icon: <DirectionLeftSecondArrowIcon className="next-icon" />}, 
{name: "DirectionRightArrowIcon", icon: <DirectionRightArrowIcon className="next-icon" />}, 
{name: "DirectionRightSecondArrowIcon", icon: <DirectionRightSecondArrowIcon className="next-icon" />}, 
{name: "DirectionsIcon", icon: <DirectionsIcon className="next-icon" />}, 
{name: "DisabilityIcon", icon: <DisabilityIcon className="next-icon" />}, 
{name: "DiscountIcon", icon: <DiscountIcon className="next-icon" />}, 
{name: "DishwasherIcon", icon: <DishwasherIcon className="next-icon" />}, 
{name: "DollarBillsIcon", icon: <DollarBillsIcon className="next-icon" />}, 
{name: "DollarCircleIcon", icon: <DollarCircleIcon className="next-icon" />}, 
{name: "DollarIcon", icon: <DollarIcon className="next-icon" />}, 
{name: "DollarSquareIcon", icon: <DollarSquareIcon className="next-icon" />}, 
{name: "DomainIcon", icon: <DomainIcon className="next-icon" />}, 
{name: "DownloadIcon", icon: <DownloadIcon className="next-icon" />}, 
{name: "EquallyIcon", icon: <EquallyIcon className="next-icon" />}, 
{name: "ExpandFullscreenIcon", icon: <ExpandFullscreenIcon className="next-icon" />}, 
{name: "FastFoodIcon", icon: <FastFoodIcon className="next-icon" />}, 
{name: "FingerIcon", icon: <FingerIcon className="next-icon" />}, 
{name: "FingerPressIcon", icon: <FingerPressIcon className="next-icon" />}, 
{name: "FishIcon", icon: <FishIcon className="next-icon" />}, 
{name: "GiftIcon", icon: <GiftIcon className="next-icon" />}, 
{name: "GivingHandIcon", icon: <GivingHandIcon className="next-icon" />}, 
{name: "GlutenFreeIcon", icon: <GlutenFreeIcon className="next-icon" />}, 
{name: "GraduationIcon", icon: <GraduationIcon className="next-icon" />}, 
{name: "GroupPeopleIcon", icon: <GroupPeopleIcon className="next-icon" />}, 
{name: "HeartIcon", icon: <HeartIcon className="next-icon" />}, 
{name: "HeartMonitorIcon", icon: <HeartMonitorIcon className="next-icon" />}, 
{name: "HinduismIcon", icon: <HinduismIcon className="next-icon" />}, 
{name: "HistoryIcon", icon: <HistoryIcon className="next-icon" />}, 
{name: "HoldIcon", icon: <HoldIcon className="next-icon" />}, 
{name: "HomeIcon", icon: <HomeIcon className="next-icon" />}, 
{name: "HomeSecondIcon", icon: <HomeSecondIcon className="next-icon" />}, 
{name: "HouseIcon", icon: <HouseIcon className="next-icon" />}, 
{name: "HouseSecondIcon", icon: <HouseSecondIcon className="next-icon" />}, 
{name: "InfoIcon", icon: <InfoIcon className="next-icon" />}, 
{name: "InfoThickIcon", icon: <InfoThickIcon className="next-icon" />}, 
{name: "LaptopComputerIcon", icon: <LaptopComputerIcon className="next-icon" />}, 
{name: "LaughingFaceIcon", icon: <LaughingFaceIcon className="next-icon" />}, 
{name: "LeafIcon", icon: <LeafIcon className="next-icon" />}, 
{name: "LibraIcon", icon: <LibraIcon className="next-icon" />}, 
{name: "ListIcon", icon: <ListIcon className="next-icon" />}, 
{name: "LoadingIcon", icon: <LoadingIcon className="next-icon" />}, 
{name: "LocationPinIcon", icon: <LocationPinIcon className="next-icon" />}, 
{name: "MailIcon", icon: <MailIcon className="next-icon" />}, 
{name: "MailSecondIcon", icon: <MailSecondIcon className="next-icon" />}, 
{name: "ManCircleSecondIcon", icon: <ManCircleSecondIcon className="next-icon" />}, 
{name: "MapIcon", icon: <MapIcon className="next-icon" />}, 
{name: "MapSecondIcon", icon: <MapSecondIcon className="next-icon" />}, 
{name: "MembershipIcon", icon: <MembershipIcon className="next-icon" />}, 
{name: "MenuIcon", icon: <MenuIcon className="next-icon" />}, 
{name: "MilkIcon", icon: <MilkIcon className="next-icon" />}, 
{name: "MinusCircleIcon", icon: <MinusCircleIcon className="next-icon" />}, 
{name: "MinusIcon", icon: <MinusIcon className="next-icon" />}, 
{name: "MinusRoundedIcon", icon: <MinusRoundedIcon className="next-icon" />}, 
{name: "MinusRoundedThickIcon", icon: <MinusRoundedThickIcon className="next-icon" />}, 
{name: "MinusThickIcon", icon: <MinusThickIcon className="next-icon" />}, 
{name: "MobileIcon", icon: <MobileIcon className="next-icon" />}, 
{name: "ModifyIcon", icon: <ModifyIcon className="next-icon" />}, 
{name: "MoneyDocumentIcon", icon: <MoneyDocumentIcon className="next-icon" />}, 
{name: "MoneyIcon", icon: <MoneyIcon className="next-icon" />}, 
{name: "MonitorIcon", icon: <MonitorIcon className="next-icon" />}, 
{name: "MoonIcon", icon: <MoonIcon className="next-icon" />}, 
{name: "NextIcon", icon: <NextIcon className="next-icon" />}, 
{name: "NoteIcon", icon: <NoteIcon className="next-icon" />}, 
{name: "NoteSecondIcon", icon: <NoteSecondIcon className="next-icon" />}, 
{name: "OpenBookIcon", icon: <OpenBookIcon className="next-icon" />}, 
{name: "PeopleIcon", icon: <PeopleIcon className="next-icon" />}, 
{name: "PerItemIcon", icon: <PerItemIcon className="next-icon" />}, 
{name: "PercentCircleIcon", icon: <PercentCircleIcon className="next-icon" />}, 
{name: "PersonCircleIcon", icon: <PersonCircleIcon className="next-icon" />}, 
{name: "PersonIcon", icon: <PersonIcon className="next-icon" />}, 
{name: "PersonSecondCircleIcon", icon: <PersonSecondCircleIcon className="next-icon" />}, 
{name: "PersonSecondIcon", icon: <PersonSecondIcon className="next-icon" />}, 
{name: "PersonSquareIcon", icon: <PersonSquareIcon className="next-icon" />}, 
{name: "PhoneIcon", icon: <PhoneIcon className="next-icon" />}, 
{name: "PickUpIcon", icon: <PickUpIcon className="next-icon" />}, 
{name: "PlayIcon", icon: <PlayIcon className="next-icon" />}, 
{name: "PluginIcon", icon: <PluginIcon className="next-icon" />}, 
{name: "PlusCircleIcon", icon: <PlusCircleIcon className="next-icon" />}, 
{name: "PlusIcon", icon: <PlusIcon className="next-icon" />}, 
{name: "PlusRoundedIcon", icon: <PlusRoundedIcon className="next-icon" />}, 
{name: "PlusRoundedThickIcon", icon: <PlusRoundedThickIcon className="next-icon" />}, 
{name: "PlusThickIcon", icon: <PlusThickIcon className="next-icon" />}, 
{name: "PositiveBarGraphIcon", icon: <PositiveBarGraphIcon className="next-icon" />}, 
{name: "PrintIcon", icon: <PrintIcon className="next-icon" />}, 
{name: "PrinterIcon", icon: <PrinterIcon className="next-icon" />}, 
{name: "PrinterSecondIcon", icon: <PrinterSecondIcon className="next-icon" />}, 
{name: "QuestionCircleIcon", icon: <QuestionCircleIcon className="next-icon" />}, 
{name: "QuestionIcon", icon: <QuestionIcon className="next-icon" />}, 
{name: "QuestionSquareIcon", icon: <QuestionSquareIcon className="next-icon" />}, 
{name: "RepeatCircleIcon", icon: <RepeatCircleIcon className="next-icon" />}, 
{name: "RepeatIcon", icon: <RepeatIcon className="next-icon" />}, 
{name: "RepeatSecondIcon", icon: <RepeatSecondIcon className="next-icon" />}, 
{name: "ResizeIcon", icon: <ResizeIcon className="next-icon" />}, 
{name: "RockIcon", icon: <RockIcon className="next-icon" />}, 
{name: "SadFaceIcon", icon: <SadFaceIcon className="next-icon" />}, 
{name: "SaladIcon", icon: <SaladIcon className="next-icon" />}, 
{name: "ScooterIcon", icon: <ScooterIcon className="next-icon" />}, 
{name: "SearchIcon", icon: <SearchIcon className="next-icon" />}, 
{name: "SearchUsersIcon", icon: <SearchUsersIcon className="next-icon" />}, 
{name: "SeatedIcon", icon: <SeatedIcon className="next-icon" />}, 
{name: "ServerIcon", icon: <ServerIcon className="next-icon" />}, 
{name: "SetLocationIcon", icon: <SetLocationIcon className="next-icon" />}, 
{name: "SettingsIcon", icon: <SettingsIcon className="next-icon" />}, 
{name: "SilverwareIcon", icon: <SilverwareIcon className="next-icon" />}, 
{name: "SmileyFaceIcon", icon: <SmileyFaceIcon className="next-icon" />}, 
{name: "SortIcon", icon: <SortIcon className="next-icon" />}, 
{name: "SpecialIcon", icon: <SpecialIcon className="next-icon" />}, 
{name: "SpecialSecondIcon", icon: <SpecialSecondIcon className="next-icon" />}, 
{name: "SpeedometerIcon", icon: <SpeedometerIcon className="next-icon" />}, 
{name: "StackedCirclesIcon", icon: <StackedCirclesIcon className="next-icon" />}, 
{name: "StarIcon", icon: <StarIcon className="next-icon" />}, 
{name: "StarListIcon", icon: <StarListIcon className="next-icon" />}, 
{name: "StarSecondIcon", icon: <StarSecondIcon className="next-icon" />}, 
{name: "StoreIcon", icon: <StoreIcon className="next-icon" />}, 
{name: "SubscriberIcon", icon: <SubscriberIcon className="next-icon" />}, 
{name: "SwitchIcon", icon: <SwitchIcon className="next-icon" />}, 
{name: "SymbolsIcon", icon: <SymbolsIcon className="next-icon" />}, 
{name: "TableIcon", icon: <TableIcon className="next-icon" />}, 
{name: "TheaterFaceIcon", icon: <TheaterFaceIcon className="next-icon" />}, 
{name: "TopArrowCircleIcon", icon: <TopArrowCircleIcon className="next-icon" />}, 
{name: "TrashIcon", icon: <TrashIcon className="next-icon" />}, 
{name: "UpSquareIcon", icon: <UpSquareIcon className="next-icon" />}, 
{name: "UpdatesIcon", icon: <UpdatesIcon className="next-icon" />}, 
{name: "VipIcon", icon: <VipIcon className="next-icon" />}, 
{name: "VolumeOffIcon", icon: <VolumeOffIcon className="next-icon" />}, 
{name: "WaiterIcon", icon: <WaiterIcon className="next-icon" />}, 
{name: "WalkInIcon", icon: <WalkInIcon className="next-icon" />}, 
{name: "WalkingPersonIcon", icon: <WalkingPersonIcon className="next-icon" />}, 
{name: "WalletCashIcon", icon: <WalletCashIcon className="next-icon" />}, 
{name: "WarningIcon", icon: <WarningIcon className="next-icon" />}, 
{name: "WindowIcon", icon: <WindowIcon className="next-icon" />}, 
{name: "WithdrawCashIcon", icon: <WithdrawCashIcon className="next-icon" />}, 
{name: "WorkBriefcaseIcon", icon: <WorkBriefcaseIcon className="next-icon" />}, 
{name: "WorldIcon", icon: <WorldIcon className="next-icon" />}, 
{name: "WorldSecondIcon", icon: <WorldSecondIcon className="next-icon" />}, 
{name: "WritingPenIcon", icon: <WritingPenIcon className="next-icon" />}, 
{name: "XIcon", icon: <XIcon className="next-icon" />}, 
{name: "XRoundedIcon", icon: <XRoundedIcon className="next-icon" />}, 
{name: "XSquareIcon", icon: <XSquareIcon className="next-icon" />}, 
{name: "ZoomInIcon", icon: <ZoomInIcon className="next-icon" />}, 
{name: "ZoomOutIcon", icon: <ZoomOutIcon className="next-icon" />}
];
  
export default icons; 
  